### ISSUE TITLE
Update all project for meet type annotation

### ISSUE THREAD

**Issue by BehindLoader** [donkey-engine/bff#10]
Make all functions, method and variables with types annotations. 
Like in `src/settings.py`

**Comment by tmcgroul** [comment]
I'll take it

**Comment by tmcgroul** [comment]
@ABSLord @BehindLoader 
I prefer use [mypy](https://github.com/python/mypy) for type checking.
But mypy required `__init__.py` in each imported folder. Newest cpython (3.6 too) interpreters implement [420 pep](https://www.python.org/dev/peps/pep-0420/) which can find module without `__init__.py`.
### Solutions
1. place in each folder `__init__.py` file
2. add to project config rule for mypy - [ignore-missing-imports](https://mypy.readthedocs.io/en/latest/config_file.html#import-discovery)

I see config some repositories and all have ignore-missing-imports rule

**Comment by tmcgroul** [comment]
# VOTING

**Comment by tmcgroul** [comment]
__init__.py

**Comment by tmcgroul** [comment]
ignore-missing-imports

**Comment by tmcgroul** [comment]
mypy can check modules in folder without `__init__.py` but show errot - `error: Cannot find module named 'src.settings'`

**Comment by BehindLoader** [comment]
@tmcgroul It seems to me that using ignore is not very good practice. That's why i choose add __init__.py

**Comment by tmcgroul** [comment]
@BehindLoader also some third party package haven't types
error looks like:
```
src/db.py:3: error: No library stub file for module 'sqlalchemy'
src/db.py:3: note: (Stub files are from https://github.com/python/typeshed)
src/db.py:4: error: No library stub file for module 'sqlalchemy.orm'
src/db.py:5: error: No library stub file for module 'sqlalchemy.ext.declarative'
```
To solve this problem maybe needed install [something like](https://github.com/dropbox/sqlalchemy-stubs). 
or ignore concrete package in config:
```
[mypy]
python_version = 3.7

# Per-module options:
[mypy-somelibrary]
ignore_missing_imports = True
```

**Comment by tmcgroul** [comment]
Think install extra-stub-packages not good solution. Sometime needed package will not have her stubs on pypi

**Comment by tmcgroul** [comment]
@BehindLoader you can check how aohttp "fight" with mypy)
https://github.com/aio-libs/aiohttp/blob/master/setup.cfg#L50

**Comment by BehindLoader** [comment]
@tmcgroul responding to [this](https://github.com/donkey-engine/bff/issues/10#issuecomment-508947523) and [this](https://github.com/donkey-engine/bff/issues/10#issuecomment-508947759).
I agree with the second statement. No need to install third party package to check SQLAlchemy types. We assume that we trust SQLAlchemy. Let them check the types in their code.

**Comment by BehindLoader** [comment]
@tmcgroul agree with you. We no need to install that package. Lets just add SQLAlchemy paths to ignore.
