### ISSUE TITLE
Setup linter

### ISSUE THREAD

**Issue by tmcgroul** [donkey-engine/bff#41]
Default linter config not enough. He must implement some plugins:
https://github.com/edaniszewski/pylint-quotes

### Motivation:
exlude TERRIBLE mistakes

### Mistakes exmples:
* [mixing single quotes with double quotes](https://github.com/donkey-engine/bff/blob/43bcfdbc6384dc0475141c933ecd9eaf3ffc7715/src/users/views/sign_up.py#L9)
* [print statement](https://github.com/donkey-engine/bff/pull/37#discussion_r300836143)

Import order also be preferable to regulate by linter

**Comment by tmcgroul** [comment]
This issue take proposals to setup pylint

**Comment by BehindLoader** [comment]
@tmcgroul 
Absolutely cool idea! I really like.

I have suggestions for this:
- I would add a rule with an empty line after the docstring. It looks more readable
- And rule that controls alphabetical order in imports

@donkey-engine/dev 
How do you like this offer?
