### ISSUE TITLE
Discuss opportunity of migration to another linter

### ISSUE THREAD

**Issue by BehindLoader** [donkey-engine/bff#48]
[wemake.services](https://github.com/wemake-services) recently released its own set of lint rules. Perhaps it can solve our problem, which is described in #41

Actually, here is the linter itself:
https://github.com/wemake-services/wemake-python-styleguide

Article on habrahabr:
https://habr.com/ru/company/oleg-bunin/blog/433480/

Docs:
https://wemake-python-stylegui.de/en/latest/

**Comment by BehindLoader** [comment]
This linter can not:

1. **Check types.** We should leave mypy
2. **Reformat code.** 
3. **Check for SyntaxError or exceptions.** We should leave the tests

https://wemake-python-stylegui.de/en/latest/#what-we-are-not

**Comment by tmcgroul** [comment]
@BehindLoader 
> We should leave mypy
> We should leave the tests

not understand

**Comment by BehindLoader** [comment]
@tmcgroul This linter does not check types and does not catch errors. So we need to leave type checker and tests and replace `pylint` to `wemake-python-styleguide`

**Comment by tmcgroul** [comment]
@BehindLoader What problem to use llinter + typechecker?

**Comment by BehindLoader** [comment]
@tmcgroul there is no problem. it's just a note on their website

**Comment by sobolevn** [comment]
Feel free to ask me any questions you have 🙂
