### ISSUE TITLE
Migrate from psycopg to aiopg

### ISSUE THREAD

**Issue by tmcgroul** [donkey-engine/bff#56]
Now synchronous postgresql driver not allow gain async application.
I do experiment with `pg_sleep` which work as `time.sleep()` for python :snake::
`/withsleep/` - route which run inside `SELECT pg_sleep(5)`. do `print('withsleep')`
`/withoutsleep/` - route which simple do `print('withoutsleep')`
I send request on `/withsleep/` and `/withoutsleep/`
In async application i expect message in app stdout
```
withoutsleep
withsleep
```
But i getting
```
withsleep
withoutsleep
```
![Peek 2019-08-27 14-42](https://user-images.githubusercontent.com/27631177/63768529-1c506500-c8d9-11e9-8f4e-dc628588f096.gif)

**Comment by BehindLoader** [comment]
It's a good idea!
I did a little research and found the best solution to solve this problem. For this task, the following packages must be implemented:
1. [`peewee`](https://pypi.org/project/peewee/) like ORM;
2. [`peewee-async`](https://pypi.org/project/peewee-async/) for asynchronous actions with database;
3. [`aiopg`](https://pypi.org/project/aiopg/) like asynchronous driver for PostgreSQL;
3. [`peewee-migrations`](https://pypi.org/project/peewee-migrations/) for migration generation.
